title: "jacobtxt"
description: "A minimal, calm journal."
url: "https://jacobbuffalo.github.io"
baseurl: "/jacobtxt"
markdown: kramdown
permalink: /blog/:title/
status: "RIP 2025 Bills season"
links:
  - name: "Letterboxd"
    url: "https://letterboxd.com/JacobRogersBUF/"
  - name: "Q1 2026 Playlist"
    url: "https://music.apple.com/us/playlist/q1-2026/pl.u-Ymb0E72cxk2ayy"
  - name: "Slow reading list"
    url: "https://www.brainpickings.org"
collections:
  posts:
    output: true
